export {
  type AbsFilePath,
  type RelFilePath,
  type UnresolvedFilePath,
  type HomeDir,
  type DisplayPath,
  type NvimCwd,
  FileCategory,
  type FileCategory as FileCategoryType,
  type FileTypeInfo,
  MAGENTA_TEMP_DIR,
  resolveFilePath,
  relativePath,
  displayPath,
  expandTilde,
  detectFileType,
  isLikelyTextFile,
  categorizeFileType,
  validateFileSize,
  FILE_SIZE_LIMITS,
} from "@magenta/core";
