name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install typescript-language-server
        run: npm install -g typescript-language-server typescript

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run typecheck
        run: npx tsc --noEmit

      - name: Run eslint
        run: npx eslint .

      - name: Run prettier check
        run: npx prettier --check .

      - name: Run tests
        run: npx vitest --threads=false
