name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: stable

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"

    - name: Install typescript-language-server
      run: bun add -g typescript-language-server typescript

    - name: Install dependencies
      working-directory: ./bun
      run: bun install --frozen-lockfile

    - name: Run tests
      working-directory: ./bun
      run: bun test
